// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbNBM2wfGW3HoG4wLCkNn8jED2QlHaEUM',
    appId: '1:901322927748:web:5ea3ad98532a5d420f1cd1',
    messagingSenderId: '901322927748',
    projectId: 'wrufirebase',
    authDomain: 'wrufirebase.firebaseapp.com',
    storageBucket: 'wrufirebase.appspot.com',
    measurementId: 'G-R1DJFC9JG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjzLaKzrWiUPh4hD65SbNBJg0TtNfcE0',
    appId: '1:901322927748:android:201e497c9f6423ef0f1cd1',
    messagingSenderId: '901322927748',
    projectId: 'wrufirebase',
    storageBucket: 'wrufirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJjJTfONKzh-HeJvS9Xo8c2tq-e4XBJao',
    appId: '1:901322927748:ios:23fe91e25e91a6520f1cd1',
    messagingSenderId: '901322927748',
    projectId: 'wrufirebase',
    storageBucket: 'wrufirebase.appspot.com',
    iosClientId:
        '901322927748-54fd34egf5bdpoakvb9ln0d766cl0clo.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterStudyMvvm',
  );
}
